// "use client"; use client 지시자 실행, 클라이언트 컴포넌트로 변경
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link';
// import Script from 'next/script';
// import { useState, useEffect } from 'react';
import Control from './Control';

export const metadata = {
  title: "Web tutorials",
  description: "Generated by ESTSOFT BOOTCAMP",
};


export default async function RootLayout({ children }) {
  /*
  client 컴포넌트 용
  const [topics, setTopics] = useState([]);//빈 배열을 초기값으로 설정
  
  useEffect(()=>{
    fetch('http://localhost:9999/topics')
    .then(res=>res.json())
    .then(result=>setTopics(result));    
  },[]); //최초 한번 실행
  */
  console.log(process.env.API_URL);
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/topics`, { next: { revalidate: 0 } });
  const topics = await res.json(); //json->object

  return (
    <>
      {/* <Script src="/main.js" strategy='afterInteractive'/> */}

      <html lang="en">
        <body>
          <nav className="navbar bg-light">
            <div className="container">
              <h1 className="logo">
                <Link href="/" className="navbar-brand">WEB</Link>
              </h1>
              <Link href='/loadmap'>Loadmap</Link>
              <ul className="nav">
                {
                  topics.map(t => {
                    return (
                      <li key={t.id} className="nav-item">
                        <Link href={`/read/${t.id}`} className="nav-link">{t.title}</Link>
                      </li>
                    )
                  })
                }
              </ul>
            </div>
          </nav>
          <main className="container">
            {children}
            <Control />
          </main>
        </body>
      </html>
    </>
  );
}