// 'use client';
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Link from 'next/link';
// import { useState } from 'react';
// import { useEffect } from 'react';

export const metadata = {
  title: "Create Next App",
  description: "Generated by Est-Soft BootCamp",
};

export default async function RootLayout({ children }) {
  // const [topics, setTopics] = useState([])
  /*
  useEffect(() => {
    fetch('http://localhost:9999/topics')
      .then(res => res.json())
      .then(result => setTopics(result))
  }, [])*/
  const res = await fetch(`http://localhost:9999/topics`,{next:{revalidate:0}})
  const topics = await res.json()

  return (
    <>
      <html lang="en">
        <body>
          <nav className="navbar bg-light">
            <div className="container">
              <h1 className='logo'>
                <Link href='/' className="navbar-brand">WEB</Link>
              </h1>
              <Link href='/loadmap' className="navbar-link">LoadMap</Link>
              <ul className="nav">
                {
                  topics.map(t => {
                    return(
                    <li className="nav-item">
                      <Link key={t.id} href={`/read/${t.id}`} className="nav-link">{t.title}</Link>
                    </li>)
                  })
                }
              </ul>
            </div>
          </nav>
          <main className="container">
            {children}
            <ul className="nav gap-1">
              <li>
                <Link href='/create' className="btn btn-primary">Create</Link>
              </li>
              <li>
                <Link href='/update/1' className="btn btn-secondary">Update</Link>
              </li>
              <li><button type="button" className="btn btn-danger">Delete</button></li>
            </ul>
          </main>
        </body>
      </html>
    </>
  );
}
